services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-bluesky}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-bluesky}
      POSTGRES_DB: ${POSTGRES_DB:-bluesky_planner}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-bluesky} -d ${POSTGRES_DB:-bluesky_planner}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://bluesky:bluesky@postgres:5432/bluesky_planner}
      NUXT_SESSION_PASSWORD: a79d5f4ac1b94bc9ac31207d2008fcee
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  postgres_data:
